DROP TABLE IF EXISTS ProductionProcess;
DROP TABLE IF EXISTS FinalProduct;
DROP TABLE IF EXISTS Containers;
DROP TABLE IF EXISTS Materials;
DROP TABLE IF EXISTS Grapes;
DROP TABLE IF EXISTS Employee;
